apiVersion: batch/v1
kind: CronJob
metadata:
  name: bricklink-order-cronjob
  labels:
    app: bricklink-order-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 10
  suspend: false
  jobTemplate:
    metadata:
      name: bricklink-order-cronjob
      labels:
        app: bricklink-order-cronjob
    spec:
      template:
        spec:
          containers:
            - name: bricklink-order-cronjob
              image: quay.io/tvattima/lego-sandbox-application:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "sandbox,kubernetes,bricklink-order-job"
              volumeMounts:
                - name: database-volume
                  mountPath: /etc/.credentials/database
          volumes:
            - name: database-volume
              projected:
                sources:
                  - secret:
                      name: database-configuration
          restartPolicy: OnFailure